---
openapi: 3.0.3
info:
  title: onecx-permission permission template import
  version: 1.0.0
servers:
  - url: "http://localhost"
paths:
  /import/permission:
    post:
      operationId: importPermission
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TemplateImport'
      responses:
        200:
          description: ok
components:
  schemas:
    TemplateImport:
      type: object
      properties:
        roles:
          $ref: '#/components/schemas/TemplateRole'
        products:
          $ref: '#/components/schemas/TemplateProduct'
    TemplateProduct:
      type: object
      nullable: false
      description: product name
      additionalProperties:
        type: object
        properties:
          applications:
            $ref: '#/components/schemas/TemplateApplication'
    TemplateApplication:
      type: object
      nullable: false
      description: application id
      additionalProperties:
        type: object
        properties:
          name:
            type: string
          description:
            type: string
          permissions:
            $ref: '#/components/schemas/TemplatePermission'
    TemplatePermission:
      type: object
      nullable: false
      description: resource id
      additionalProperties:
        $ref: '#/components/schemas/TemplateAction'
    TemplateAction:
      type: object
      nullable: false
      description: action id, description
      additionalProperties:
        type: string
    TemplateRole:
      type: object
      nullable: false
      description: role name
      additionalProperties:
        properties:
          description:
            type: string
          assignments:
            $ref: '#/components/schemas/TemplateProductAssignment'
    TemplateProductAssignment:
      type: object
      nullable: false
      description: product name
      additionalProperties:
        $ref: '#/components/schemas/TemplateAppAssignment'
    TemplateAppAssignment:
      type: object
      nullable: false
      description: application id
      additionalProperties:
        $ref: '#/components/schemas/TemplateAssignment'
    TemplateAssignment:
      type: object
      nullable: false
      description: action
      additionalProperties:
        type: array
        items:
          type: string