---
openapi: 3.0.3
info:
  title: onecx-permission operator service
  description: This API provides endpoints to manage Permissions by the onecx-permission-operator
  version: 1.0.0
servers:
  - url: "http://onecx-permission-svc:8080"
tags:
  - name: permissionOperator
    description: Manage Permissions
paths:
  /operator/v1/{productName}/{appId}:
    put:
      security:
        - oauth2: [ ocx-pm:write ]
      tags:
        - permissionOperator
      description: Creates or updates permission for application by product name and appId.
      operationId: createOrUpdatePermission
      parameters:
        - name: productName
          in: path
          description: Product name
          required: true
          schema:
            type: string
        - name: appId
          in: path
          description: Application ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PermissionRequest'
      responses:
        200:
          description: Permission updated successfully
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.simple.api/token
          scopes:
            ocx-pm:write: Grants write access
  schemas:
    PermissionRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        permissions:
          type: array
          items:
            $ref: '#/components/schemas/Permission'
    Permission:
      type: object
      required:
        - resource
        - action
      properties:
        resource:
          type: string
        action:
          type: string
        description:
          type: string
    ProblemDetailResponse:
      type: object
      properties:
        errorCode:
          type: string
        detail:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailParam'
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailInvalidParam'
    ProblemDetailParam:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ProblemDetailInvalidParam:
      type: object
      properties:
        name:
          type: string
        message:
          type: string