---
openapi: 3.0.3
info:
  title: onecx-permission permission import from file during the start of the application
  version: 1.0.0
servers:
  - url: "http://localhost"
paths:
  /import/permission:
    post:
      operationId: importPermission
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataImport'
      responses:
        200:
          description: ok
components:
  schemas:
    DataImport:
      type: object
      properties:
        tenants:
          $ref: '#/components/schemas/DataImportTenant'
        products:
          $ref: '#/components/schemas/DataImportProduct'
    DataImportProduct:
      type: object
      nullable: false
      description: product name
      additionalProperties:
        type: object
        properties:
          applications:
             $ref: '#/components/schemas/DataImportApplication'
    DataImportApplication:
      type: object
      nullable: false
      description: application id
      additionalProperties:
        type: object
        properties:
          name:
            type: string
          description:
            type: string
          permissions:
            $ref: '#/components/schemas/DataImportApplicationPermission'
    DataImportApplicationPermission:
      type: object
      nullable: false
      description: resource id
      additionalProperties:
        $ref: '#/components/schemas/DataImportPermissionAction'
    DataImportPermissionAction:
      type: object
      nullable: false
      description: action id, description
      additionalProperties:
        type: string
    DataImportTenant:
      type: object
      nullable: false
      description: tenant id
      additionalProperties:
        type: object
        properties:
          roles:
            $ref: '#/components/schemas/DataImportTenantRole'
    DataImportTenantRole:
      type: object
      nullable: false
      description: role name
      additionalProperties:
        properties:
          description:
            type: string
          assignments:
            $ref: '#/components/schemas/DataImportTenantProductAssignment'
    DataImportTenantProductAssignment:
      type: object
      nullable: false
      description: product name
      additionalProperties:
        $ref: '#/components/schemas/DataImportTenantProductApplicationAssignment'
    DataImportTenantProductApplicationAssignment:
      type: object
      nullable: false
      description: application id
      additionalProperties:
        $ref: '#/components/schemas/DataImportTenantAssignment'
    DataImportTenantAssignment:
      type: object
      nullable: false
      description: action
      additionalProperties:
        type: array
        items:
          type: string